Почему Pytorch?
1. Pytorch просто использовать
2. Мощная поддержка GPU
3. Много имплементированных алгоритмов
4. Хорошо подходит для академических исследований с данными 
5. Автоматическое дифференцирование вычислительного графа
6. Похож на Numpy

Другие фреймворки: Pytorch, Tensorflow, Caffe, Chainer, MXNet, Keras


1. Матричное умножение

В Pytorch есть экивалент Numpy array - это torch tensor 

In [0]:
import torch

torch.tensor([[2,3,5],[1,2,9]])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [0]:
import numpy as np

np.array([[2,3,5],[1,2,9]])

array([[2, 3, 5],
       [1, 2, 9]])

In [0]:
torch.rand((2,2)) # random matrix

tensor([[0.8459, 0.7135],
        [0.9312, 0.1722]])

In [0]:
a_t = torch.zeros(2,2)
b_t = torch.ones(2,2)
c_t = torch.eye(2,2)

a_n = np.zeros((2,2))
b_n = np.ones((2,2))
c_n = np.identity(2)


In [0]:
d_t = torch.from_numpy(c_n)
d_n = c_t.numpy()

In [0]:
torch.matmul(a_t,b_t)

tensor([[0., 0.],
        [0., 0.]])

In [0]:
a_t.shape

torch.Size([2, 2])

Давайте начнем практиковать построение тензоров в библиотеке PyTorch. Как вы знаете, тензоры - это массивы с произвольным числом измерений, соответствующих ndarrays NumPy. Вы собираетесь создать случайный тензор размером 3 на 3 и установить его в переменную your_first_tensor. Затем вам нужно будет напечатать его. Наконец, вычислите его размер в переменной tenor_size и выведите его значение.

In [0]:
# Import torch
import torch

# Create random tensor of size 3 by 3
your_first_tensor = 

# Calculate the shape of the tensor
tensor_size = 

# Print the values of the tensor and its shape
print()
print()

Давайте поэкспериментируем с этими двумя типами матриц. Вы собираетесь построить матрицу из них с формой 3 на 3, называемую tenns_of_ones, и единичную матрицу той же формы, называемую identity_tensor. Мы посмотрим, что произойдет, когда мы умножим эти две матрицы, и что произойдет, если мы сделаем их поэлементное умножение.

In [0]:
# Create a matrix of ones with shape 3 by 3
tensor_of_ones = 

# Create an identity matrix with shape 3 by 3
identity_tensor = 

# Do a matrix mulitplication of tensor_of_ones with identity_tensor
matrices_multiplied = 
print()

Pytorch оперирует вычислительными графами. 
Прямой и обратный шаг - важные составляющие вычислений и в нейронной сети. Вспоминаем прямой проход по графу

2. Прямой проход (Forward pass)

Давайте сделаем что-то похожее на нейронную сеть. Расчетный граф приведен ниже. Вы собираетесь инициализировать 3 больших случайных тензора, а затем выполнить операции, как указано в вычислительном графе. Последняя операция - это среднее значение тензора, данное torch.mean (your_tensor).

![](https://drive.google.com/uc?export=view&id=1d_EZNaGCHpVx89MFZga11zycok-4dRZM)

In [0]:
# Initialize tensors x, y and z
x = torch.rand(____, ____)
y = ____
z = ____

# Multiply x with y
q = ____

# Multiply elementwise z with q
f = ____

mean_f = torch.mean(f)
print(mean_f)

3. Backpropagation шаг осуществляется посредством автодифференцирования в Pytorch. Вспоминаем обратный проход по графу и вычисление градиента

![](https://drive.google.com/uc?export=view&id=1-heFApDjrJJG9PHvsBQ5kKERx5_zKVuZ)

![](https://drive.google.com/uc?export=view&id=1evwhUrBrBepGPXbL2RraBXkSgWz_K-eo)

In [0]:
# Initialize x, y and z to values 4, -3 and 5
x = torch.tensor(4., ____)
y = torch.tensor(____., ____)
z = ____

# Set q to sum of x and y, set f to product of q with z
q = ____
f = ____

# Compute the derivatives
f.____

# Print the gradients
print("Gradient of x is: " + str(____))
print("Gradient of y is: " + str(____))
print("Gradient of z is: " + str(____))

Помните упражнение в прямом проходе? Теперь, когда вы знаете, как вычислять производные, давайте сделаем шаг вперед и начнем вычислять градиенты (производные от тензоров) вычислительного графа, построенного вами тогда. 

In [0]:
# Multiply tensors x and y
q = ____

# Elementwise multiply tensors z with q
f = ____

mean_f = torch.mean(f)

# Calculate the gradients
____

4. Полносвязные нейронные сети

In [0]:
import torch

input_layer = torch.rand(10)

w1 = torch.rand(10,20)
w2 = torch.rand(20,20)
w3 = torch.rand(20,4)

h1 = torch.matmul(input_layer,w1)
h2 = torch.matmul(h1,w2)

output_layer = torch.matmul(h2,w3)

print(output_layer)

Вы собираетесь построить нейронную сеть в PyTorch, используя сложный путь. В качестве входных данных будут использоваться изображения размером (28, 28), то есть изображения, содержащие 784 пикселя. Ваша сеть будет содержать слой input_layer (предоставляется для вас), скрытый слой с 200 единицами и выходной слой с 10 классами. Входной слой уже создан для вас. Вы собираетесь создать весовые коэффициенты, а затем выполнить умножение матриц, получая результаты из сети.

In [0]:
# Initialize the weights of the neural network
weight_1 = torch.rand(____, ____)
weight_2 = ____

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(____, ____)

# Multiply hidden_1 with weight_2
output_layer = ____
print(output_layer)

In [0]:
import torch
import torch.nn as nn

class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = Linear(10,20)
    self.fc2 = Linear(20,20)
    self.output = nn.Linear(20,4)
    
  def forward(self,x):
    x = self.fc1(x)
    x = self.fc2(x)
    x = self.output(x)
    return x

5. Ваша первая нейронная сеть PyTorch

Вы собираетесь построить ту же нейронную сеть, которую вы создали в предыдущем упражнении, но теперь с помощью метода PyTorch. Напоминаем, что у вас есть 784 единицы на входном слое, 200 скрытых единиц и 10 единиц на выходном слое.

In [0]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate all 2 linear layers  
        self.fc1 = nn.Linear(____, ____)
        self.fc2 = ____

    def forward(self, x):
      
        # Use the instantiated layers and return x
        x = self.fc1(x)
        x = ____
        return ____

6. Функции активации (нелинейность)

Многослойные нейронные сети без функции активации эквивалентны сети с одним слоем (линейной регрессии)

In [0]:
# Initialize input layer, weight_1, weight_2, weight_3

# Calculate the first and second hidden layer
hidden_1 = torch.matmul(input_layer, weight_1)
hidden_2 = torch.matmul(hidden_1, weight_2)

# Calculate the output
print(torch.matmul(hidden_2, weight_3))

# Calculate weight_composed_1 and weight
weight_composed_1 = torch.matmul(weight_1, weight_2)
weight = torch.matmul(weight_composed_1, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

In [0]:
# Apply non-linearity on hidden_1 and hidden_2
hidden_1_activated = relu(torch.matmul(input_layer, weight_1))
hidden_2_activated = relu(torch.matmul(hidden_1_activated, weight_2))
print(torch.matmul(hidden_2_activated, weight_3))

# Apply non-linearity in the product of first two weights. 
weight_composed_1_activated = relu(torch.matmul(weight_1, weight_2))

# Multiply `weight_composed_1_activated` with `weight_3
weight = torch.matmul(weight_composed_1_activated, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

Нейронные сети не должны иметь одинаковое количество единиц в каждом слое. Здесь вы снова поэкспериментируете с функцией активации ReLU, но на этот раз у нас будет разное количество единиц в слоях нейронной сети. Входной слой по-прежнему будет иметь 4 объекта, но тогда первый скрытый слой будет иметь 6 единиц, а выходной слой будет иметь 2 единицы.

![](https://drive.google.com/uc?export=view&id=1cAZ4wYpgUOUFOo4IiHD9MaNuFSOY4YOo)

In [0]:
# Instantiate ReLU activation function as relu
import torch.nn as nn
relu = nn.ReLU()

# Initialize weight_1 and weight_2 with random numbers
weight_1 = torch.rand(4, 6)
weight_2 = torch.rand(6, 2)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Apply ReLU activation function over hidden_1 and multiply with weight_2
hidden_1_activated = relu(hidden_1)
print(torch.matmul(hidden_1_activated, weight_2))

7. Функция потерь (кросс-энтропия)

Функция потерь должна быть дифференцируема, какая нибудь доля неправильных ответов - не подойдет. Кросс-энтропия хорошо работает для большинства задач. 

![](https://drive.google.com/uc?export=view&id=1x2kwtTqIVJyDP6Wd8BqTK6cd0pgJF1lH)

Функция расчета потерь в PyTorch
Вы собираетесь написать код предыдущего упражнения и убедиться, что мы правильно рассчитали потери. Прогнозируемые баллы -1,2 для класса 0 (кошка), 0,12 для класса 1 (автомобиль) и 4,8 для класса 2 (лягушка). Основная правда - класс 2 (лягушка). Вычислить функцию потерь в PyTorch.

In [0]:
# Initialize the scores and ground truth
logits = torch.tensor([[-1.2,0.12,4.8]])
ground_truth = torch.tensor([2])

# Instantiate cross entropy loss
criterion = nn.CrossEntropyLoss()

# Compute and print the loss
loss = criterion(logits,ground_truth)
print(loss)

Функция потери случайных результатов
Если нейронная сеть предсказывает случайные оценки, какова будет ее функция потерь? Давайте выясним это в PyTorch. В нейронной сети будет 1000 классов rand(1,1000), каждый из которых имеет случайный счет. Для наземной правды у него будет класс 111. Рассчитайте функцию потерь.

In [0]:
# Import torch and torch.nn
____
____

# Initialize logits and ground truth
logits = ____
ground_truth = ____

# Instantiate cross-entropy loss
____

# Calculate and print the loss
loss = ____
____

###  8. Работа с датасетами в Pytorch
MNIST и CIFAR-10 датасет

In [0]:
import torch
import torchvision
import torch.utils.data 
import torchvision.transforms as transforms

In [0]:
transform = transforms.Compose(
    [transforms.ToTensor(), 
    transforms.Normalize((0.4941, 0.48216, 0.44653), (0.24703, 0.24349, 0.26159))]) # mean and std for each channel

#### Datasets и Dataloaders

In [0]:
trainset  = torchvision.datasets.CIFAR10(root='./data', train=True, 
                                         download=True, transform=transform)

testset = torchvision.datasets.CIFAR10(root='./data', train=False, 
                                         download=True, transform=transform)

0it [00:00, ?it/s]

170500096it [00:03, 43252610.60it/s]                               


Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [0]:
%ll

total 8
drwxr-xr-x 3 root 4096 Oct  8 18:42 data/
drwxr-xr-x 1 root 4096 Aug 27 16:17 sample_data/


In [0]:
trainloader = torch.utils.data.DataLoader(trainset, batch_size=32,
                                          shuffle=True, num_workers=4)

testloader = torch.utils.data.DataLoader(testset, batch_size=32,
                                          shuffle=False, num_workers=4) # processes

In [0]:
print(trainloader.dataset.data.shape, testloader.dataset.data.shape)

(50000, 32, 32, 3) (10000, 32, 32, 3)


In [0]:
testloader.batch_size

32

In [0]:
testloader.sampler

Подготовка набора данных MNIST
Вы собираетесь подготовить загрузчики данных для обучения и тестирования MNIST. Как мы объяснили в лекции, MNIST имеет некоторые отличия от CIFAR-10, при этом основное отличие состоит в том, что изображения MNIST имеют оттенки серого (на основе 1 канала) вместо RGB (3 канала). mean = 0.1307, std = 0.3081

In [0]:
# Transform the data to torch tensors and normalize it 
transform = transforms.Compose([transforms.____,
								transforms.____((____), ((____)))])

# Prepare training set and testing set
trainset = torchvision.datasets.MNIST('mnist', train=____, 
									  download=____, transform=____)
testset = ____('mnist', ____,
			   ____, ____)

# Prepare training loader and testing loader
trainloader = torch.utils.data.DataLoader(____, ____,
                                          ____, num_workers=0)
testloader = torch.utils.data.DataLoader(____, ____,
										 ____, num_workers=0) 

### 9. Обучение нейронных сетей

In [0]:
trainset  = torchvision.datasets.CIFAR10(root='./data', train=True, 
                                         download=True, transform=transform)

testset = torchvision.datasets.CIFAR10(root='./data', train=False, 
                                         download=True, transform=transform)

Files already downloaded and verified
Files already downloaded and verified


In [0]:
trainloader = torch.utils.data.DataLoader(trainset, batch_size=32,
                                          shuffle=True, num_workers=4)

testloader = torch.utils.data.DataLoader(testset, batch_size=32,
                                          shuffle=False, num_workers=4) # processes

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import optim


class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(32*32*3,500) # 500 нейронов в первом слое
    self.fc2 = nn.Linear(500,10) # 10 классов
    
  def forward(self,x):
    x = F.relu(self.fc1(x))
    x = self.fc2(x)
    return x

In [0]:
net  = Net()

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(net.parameters(), lr=3e-04)

for epoch in range(10):
  for i, data in enumerate(trainloader, 0):
    #Get the inputs
    inputs, labels = data
    inputs = inputs.view(-1, 32*32*3)
    
    #Zero the parameter gradient 
    optimizer.zero_grad()
    
    # Forward + backward + optimize
    
    outputs = net(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()

KeyboardInterrupt: ignored

In [0]:
correct, total = 0, 0
predictions = []
net.eval()
for i, data in enumerate(testloader, 0):
  inputs, data = data
  outputs = net(inputs)
  _, predicted = torch.max(outputs.data, 1)
  predictions.append(outputs)
  total += labels.size(0)
  correct += (predicted == labels).sum().item()
  
print('The testing set accuracy of the network is: %d %%' % (100*correct/total))

Создайте класс для нейронной сети, которая будет использоваться для обучения на наборе данных MNIST. Набор данных содержит изображения (28, 28, 1), поэтому вы должны вычесть размер входного слоя. Для скрытого слоя используйте 200 нейронов, а для выходного слоя - 10 нейронов (по 1 для каждого класса). Для функции активации используйте relu функциональным способом (nn.Functional как F)

In [0]:
# Define the class Net
____:
    def __init__(self):    
    	# Define all the parameters of the net
        super(Net, self).__init__()
        self.fc1 = nn.Linear(____ * ____ * ____, ____)
        self.fc2 = ____

    def forward(self, x):   
    	# Do the forward pass
        x = F.relu(self.fc1(____))
        x = self.____(____)
        return ____

In [0]:
# Instantiate the Adam optimizer and Cross-Entropy loss function
optimizer = optim.Adam(____.parameters(), lr=3e-4)
criterion = nn.____
  
for batch_idx, data_target in enumerate(train_loader):
    data = data_target[0]
    target = data_target[1]
    data = data.view(-1, 28 * 28)
    optimizer.zero_grad()

    # Complete a forward pass
    output = model(____)

    # Compute the loss, gradients and change the weights
    loss = ____
    loss.____
    optimizer.____

Теперь, когда вы обучили сеть, используйте ее для прогнозирования данных в тестовом наборе данных. Сеть называется - модель (как в предыдущем упражнении), а загрузчик называется test_loader. Мы уже инициализировали переменные total и correct до 0.

In [0]:
# Set the model in eval mode
model.____

for i, data in enumerate(test_loader, 0):
    inputs, labels = data
    
    # Put each image into a vector
    inputs = inputs.view(-1, ____)
    
    # Do the forward pass and get the predictions
    outputs = ____
    _, outputs = ____
    total += labels.size(0)
    correct += (outputs == labels).sum().item()
print('The testing set accuracy of the network is: %d %%' % (100 * correct / total))